import { User, CommissionEntry } from '@/types/types'

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Sibli Sadik',
    phoneNumber: '018XXXXXXXX',
    region: 'Dhaka',
    username: 'sibli_admin',
    password: 'admin123',
    role: 'admin',
  },
  {
    id: '2',
    name: 'Syful Islam',
    phoneNumber: '01XXXXXXXXX',
    region: 'Dhaka',
    username: 'syful_islam',
    password: 'user123',
    role: 'user',
  },
  {
    id: '3',
    name: 'Tawhid Chowdhury',
    phoneNumber: '01XXXXXXXXX',
    region: 'Chattogram',
    username: 'tawhid_chowdhury',
    password: 'user456',
    role: 'user',
  },
  {
    id: '4',
    name: 'Nurul Alam Khan',
    phoneNumber: '01XXXXXXXXX',
    region: 'Dhaka',
    username: 'nakhan',
    password: '12345',
    role: 'user',
  },
  {
    id: '5',
    name: 'Admin Nurul Alam Khan',
    phoneNumber: '01XXXXXXXXX',
    region: 'Dhaka',
    username: 'na.khan',
    password: '12345',
    role: 'admin',
  },
  {
    id: '6',
    name: 'Zafirul Islam Mondol',
    phoneNumber: '01XXXXXXXXX',
    region: 'Dhaka',
    username: 'Zafirul_Islam',
    password: 'user789',
    role: 'user',
  },
   {
      id: '7',
      name: 'Tumpa Rani Sarkar',
      phoneNumber: '01XXXXXXXXX',
      region: 'Sylhet',
      username: 'tumpa_sarkar',
      password: 'tumpa12345',
      role: 'user',
    },
]

export const mockCommissionEntries: CommissionEntry[] = [
  {
      id: '1',
      merchantName: 'ABC Electronics',
      invoiceNumber: 'INV-001',
      yearMonth: [{ year: '2023', month: 'January', billAmount: '5000' }],
      collectedAmount: 5000,
      collectionDate: '2023-01-15',
      bankName: 'BRAC Bank',
      checkNumber: 'CHK-001',
      clearingBranch: 'Gulshan',
      checkSubmissionDate: '2023-01-16',
      collectionOfficer: 'Syful Islam',
      region: 'Dhaka',
      createdAt: '2023-01-15T10:00:00Z',
      updatedAt: '2023-01-15T10:00:00Z',
    },
    {
      id: '2',
      merchantName: 'XYZ Appliances',
      invoiceNumber: 'INV-002',
      yearMonth: [{ year: '2023', month: 'February', billAmount: '7500' }],
      collectedAmount: 7500,
      collectionDate: '2023-02-20',
      bankName: 'Dutch-Bangla Bank',
      checkNumber: 'CHK-002',
      clearingBranch: 'Motijheel',
      checkSubmissionDate: '2023-02-21',
      collectionOfficer: 'Tawhid Chowdhury',
      region: 'Chattogram',
      createdAt: '2023-02-20T11:00:00Z',
      updatedAt: '2023-02-20T11:00:00Z',
    },
    {
      id: '3',
      merchantName: 'PQR Gadgets',
      invoiceNumber: 'INV-003',
      yearMonth: [{ year: '2023', month: 'March', billAmount: '6000' }],
      collectedAmount: 6000,
      collectionDate: '2023-03-10',
      bankName: 'Sonali Bank',
      checkNumber: 'CHK-003',
      clearingBranch: 'Dhanmondi',
      checkSubmissionDate: '2023-03-11',
      collectionOfficer: 'Syful Islam',
      region: 'Dhaka',
      createdAt: '2023-03-10T09:00:00Z',
      updatedAt: '2023-03-10T09:00:00Z',
    },
    {
      id: '4',
      merchantName: 'LMN Computers',
      invoiceNumber: 'INV-004',
      yearMonth: [{ year: '2022', month: 'December', billAmount: '8000' }],
      collectedAmount: 8000,
      collectionDate: '2022-12-05',
      bankName: 'Islami Bank',
      checkNumber: 'CHK-004',
      clearingBranch: 'Uttara',
      checkSubmissionDate: '2022-12-06',
      collectionOfficer: 'Tumpa Rani Sarkar',
      region: 'Sylhet',
      createdAt: '2022-12-05T14:30:00Z',
      updatedAt: '2022-12-05T14:30:00Z',
    },
    {
      id: '5',
      merchantName: 'EFG Mobile Shop',
      invoiceNumber: 'INV-005',
      yearMonth: [{ year: '2023', month: 'April', billAmount: '5500' }],
      collectedAmount: 5500,
      collectionDate: '2020-04-18',
      bankName: 'Prime Bank',
      checkNumber: 'CHK-005',
      clearingBranch: 'Banani',
      checkSubmissionDate: '2020-04-19',
      collectionOfficer: 'Tawhid Chowdhury',
      region: 'Chattogram',
      createdAt: '2023-04-18T16:45:00Z',
      updatedAt: '2023-04-18T16:45:00Z',
    },
    {
      id: '6',
      merchantName: 'RST Supermarket',
      invoiceNumber: 'INV-006',
      yearMonth: [{ year: '2023', month: 'May', billAmount: '9000' }],
      collectedAmount: 9000,
      collectionDate: '2021-05-22',
      bankName: 'Eastern Bank',
      checkNumber: 'CHK-006',
      clearingBranch: 'Mirpur',
      checkSubmissionDate: '2023-05-23',
      collectionOfficer: 'Syful Islam',
      region: 'Dhaka',
      createdAt: '2023-05-22T11:20:00Z',
      updatedAt: '2023-05-22T11:20:00Z',
    },
    {
      id: '7',
      merchantName: 'UVW Electronics',
      invoiceNumber: 'INV-007',
      yearMonth: [{ year: '2022', month: 'November', billAmount: '7200' }],
      collectedAmount: 7200,
      collectionDate: '2022-11-30',
      bankName: 'City Bank',
      checkNumber: 'CHK-007',
      clearingBranch: 'Mohakhali',
      checkSubmissionDate: '2022-12-01',
      collectionOfficer: 'Tumpa Rani Sarkar',
      region: 'Sylhet',
      createdAt: '2022-11-30T09:15:00Z',
      updatedAt: '2022-11-30T09:15:00Z',
    },
    {
      id: '8',
      merchantName: 'HIJ Furniture',
      invoiceNumber: 'INV-008',
      yearMonth: [{ year: '2023', month: 'June', billAmount: '11000' }],
      collectedAmount: 11000,
      collectionDate: '2023-06-14',
      bankName: 'Standard Chartered',
      checkNumber: 'CHK-008',
      clearingBranch: 'Gulshan',
      checkSubmissionDate: '2023-06-15',
      collectionOfficer: 'Tawhid Chowdhury',
      region: 'Chattogram',
      createdAt: '2023-06-14T13:40:00Z',
      updatedAt: '2023-06-14T13:40:00Z',
    },
    {
      id: '9',
      merchantName: 'KLM Pharmacy',
      invoiceNumber: 'INV-009',
      yearMonth: [{ year: '2023', month: 'July', billAmount: '4800' }],
      collectedAmount: 4800,
      collectionDate: '2023-07-05',
      bankName: 'Pubali Bank',
      checkNumber: 'CHK-009',
      clearingBranch: 'Uttara',
      checkSubmissionDate: '2023-07-06',
      collectionOfficer: 'Syful Islam',
      region: 'Dhaka',
      createdAt: '2023-07-05T10:30:00Z',
      updatedAt: '2023-07-05T10:30:00Z',
    },
    {
      id: '10',
      merchantName: 'NOP Stationery',
      invoiceNumber: 'INV-010',
      yearMonth: [{ year: '2022', month: 'October', billAmount: '3500' }],
      collectedAmount: 3500,
      collectionDate: '2022-10-12',
      bankName: 'Mutual Trust Bank',
      checkNumber: 'CHK-010',
      clearingBranch: 'Dhanmondi',
      checkSubmissionDate: '2022-10-13',
      collectionOfficer: 'Tumpa Rani Sarkar',
      region: 'Sylhet',
      createdAt: '2022-10-12T15:20:00Z',
      updatedAt: '2022-10-12T15:20:00Z',
    },
    {
      id: '11',
      merchantName: 'QRS Bookstore',
      invoiceNumber: 'INV-011',
      yearMonth: [{ year: '2023', month: 'August', billAmount: '6200' }],
      collectedAmount: 6200,
      collectionDate: '2023-08-18',
      bankName: 'One Bank',
      checkNumber: 'CHK-011',
      clearingBranch: 'Mirpur',
      checkSubmissionDate: '2023-08-19',
      collectionOfficer: 'Tawhid Chowdhury',
      region: 'Chattogram',
      createdAt: '2023-08-18T11:45:00Z',
      updatedAt: '2023-08-18T11:45:00Z',
    },
    {
      id: '12',
      merchantName: 'TUV Cosmetics',
      invoiceNumber: 'INV-012',
      yearMonth: [{ year: '2023', month: 'September', billAmount: '8800' }],
      collectedAmount: 8800,
      collectionDate: '2023-09-25',
      bankName: 'Southeast Bank',
      checkNumber: 'CHK-012',
      clearingBranch: 'Banani',
      checkSubmissionDate: '2023-09-26',
      collectionOfficer: 'Syful Islam',
      region: 'Dhaka',
      createdAt: '2023-09-25T14:10:00Z',
      updatedAt: '2023-09-25T14:10:00Z',
    },
    {
      id: '13',
      merchantName: 'WXY Sportswear',
      invoiceNumber: 'INV-013',
      yearMonth: [{ year: '2022', month: 'September', billAmount: '7100' }],
      collectedAmount: 7100,
      collectionDate: '2022-09-08',
      bankName: 'NCC Bank',
      checkNumber: 'CHK-013',
      clearingBranch: 'Mohakhali',
      checkSubmissionDate: '2022-09-09',
      collectionOfficer: 'Tumpa Rani Sarkar',
      region: 'Sylhet',
      createdAt: '2022-09-08T09:55:00Z',
      updatedAt: '2022-09-08T09:55:00Z',
    },
    {
      id: '14',
      merchantName: 'ZAB Toys',
      invoiceNumber: 'INV-014',
      yearMonth: [{ year: '2023', month: 'October', billAmount: '5300' }],
      collectedAmount: 5300,
      collectionDate: '2023-10-30',
      bankName: 'Dhaka Bank',
      checkNumber: 'CHK-014',
      clearingBranch: 'Uttara',
      checkSubmissionDate: '2023-10-31',
      collectionOfficer: 'Tawhid Chowdhury',
      region: 'Chattogram',
      createdAt: '2023-10-30T16:25:00Z',
      updatedAt: '2023-10-30T16:25:00Z',
    },
    {
      id: '15',
      merchantName: 'CDE Groceries',
      invoiceNumber: 'INV-015',
      yearMonth: [{ year: '2023', month: 'November', billAmount: '9500' }],
      collectedAmount: 9500,
      collectionDate: '2023-11-15',
      bankName: 'Bank Asia',
      checkNumber: 'CHK-015',
      clearingBranch: 'Gulshan',
      checkSubmissionDate: '2023-11-16',
      collectionOfficer: 'Syful Islam',
      region: 'Dhaka',
      createdAt: '2023-11-15T10:05:00Z',
      updatedAt: '2023-11-15T10:05:00Z',
    },
  {
    id: '16',
    merchantName: 'AC WORLD ELECTRONICS LTD',
    invoiceNumber: 'INV-016',
    yearMonth: [{ year: '2023', month: 'December', billAmount: '8500' }],
    collectedAmount: 8500,
    collectionDate: '2023-12-05',
    bankName: 'Sonali Bank',
    checkNumber: 'CHK-016',
    clearingBranch: 'Motijheel',
    checkSubmissionDate: '2023-12-06',
    collectionOfficer: 'Zafirul Islam Mondol',
    region: 'Dhaka',
    createdAt: '2023-12-05T09:30:00Z',
    updatedAt: '2023-12-05T09:30:00Z',
  },
  {
    id: '17',
    merchantName: 'BUTTERFLY MARKETING LTD',
    invoiceNumber: 'INV-017',
    yearMonth: [{ year: '2023', month: 'December', billAmount: '7800' }],
    collectedAmount: 7800,
    collectionDate: '2023-12-10',
    bankName: 'Janata Bank',
    checkNumber: 'CHK-017',
    clearingBranch: 'Gulshan',
    checkSubmissionDate: '2023-12-11',
    collectionOfficer: 'Zafirul Islam Mondol',
    region: 'Dhaka',
    createdAt: '2023-12-10T11:15:00Z',
    updatedAt: '2023-12-10T11:15:00Z',
  },
]

export const mockMerchants = [
  "AC WORLD ELECTRONICS LTD",
  "BUTTERFLY MARKETING LTD",
  "COMPLETE KITCHEN",
  "COMPUTER EXPLORE",
  "COMPUTER ZONE",
  "ELECTRA INTERNATIONAL",
  "ELECTRO MART LIMITED",
  "ESQUIRE ELECTRONICS LTD",
  "HTS CORPORATION LTD",
  "JAMUNA ELECTRONICS & AUTOMOBILES LTD",
  "M.R. ELECTRONICS",
  "METROCEM TECHNOLOGIES LIMITED",
  "RANGS ELECTRONICS LTD",
  "REDGREEN CORPORATION",
  "SINGER BANGLADESH LIMITED",
  "TRANSCOM ELECTRONICS LTD",
  "FAIR ELECTRONICS LTD.",
  "WALTON PLAZA",
  "BEST ELECTRONICS LTD.",
  "AZUBA ELECTRONICS LTD.",
  "COMPUTER LAND",
  "CREATIVE MARKETING COMPANY",
  "NADIM ELECTRONICS",
  "COMPUTER VILLAGE",
  "ER ELECTRONICS",
  "SHAMIM ELECTRONICS",
  "M/S. L. K. TRADING",
  "PREMIER ELECTRONICS PLUS",
  "NEW RADIO VOICE",
  "RYANS IT LTD.",
  "M/S HABIB ELECTRONICS",
  "MAX ELECTRONICS",
  "AB ELECTRONICS",
  "SENS",
  "TV HUT",
  "RS COM BD",
  "S.Y.A. ELECTRONICS",
  "A/RTM DISTRIBUTION FIRM",
  "Lotus International",
  "Buy N Save Electronics",
  "Gadget 360° A",
  "Gadgets Planet",
  "Ayan Electronics",
  "New Camera World",
  "Camera Zone",
  "Super Electronics",
  "M/S Khan Electronics",
  "Rangs Industry",
  "Brothers & Tech",
  "Shan Electronics",
  "US-Bangla Airlines Limited",
  "BROTHERS FURNITURE LTD",
  "HATIL COMPLEX LTD",
  "HI-TECH FURNITURE",
  "MUNTAFI FURNITURE LTD",
  "NADIA FURNITURE LTD",
  "NAVANA FURNITURE LIMITED",
  "SHAYMA FURNITURE",
  "WOODIES",
  "OMEGA HOME SOLUTION",
  "FURNITURE POINT",
  "WOOD HEAVEN MART",
  "NEW UNIVERSAL FURNISHER'S",
  "JMAK Furniture Limited",
  "New Lam Yea Furniture",
  "Green World Furniture & Interior",
  "Raz Furniture BD",
  "Opera Furniture",
  "MS Shiza Enterprise",
  "GITANJALI JEWELLERS",
  "SANDWIP GRIHINEE JEWELLERS",
  "PURNIMA JEWELLERS",
  "BADHUMITA JEWELLERS",
  "AL-HASSAN DIAMOND GALLERY LTD.",
  "The Sandwip Watch",
  "BIO-XIN COSMECEUTICALS",
  "WEAVERS FURNISHING LTD",
  "New Gini Jewelers",
  "Diamond Palace",
  "Royal Diamond",
  "New Royal Diamond",
  "Biyerbazaar.com",
  "BB Bridal Makeover Studio & Salon",
  "Diamond Plaza",
  "GOLD WORLD & DIAMOND",
  "Shovan Jewellers",
  "CELLULAR MOBILE PTE LTD",
  "COMPUSTAR PVT LTD",
  "FAIR DISTRIBUTION LIMITED",
  "FARHAN TELECOM",
  "ONLINE BANGLA SHOP",
  "RONY ENTERPRISE",
  "S K TOUCH",
  "SOLAR ELECTRO BANGLADESH LTD",
  "TRANSCOM MOBILE LTD",
  "APPLE GADGETS Ltd.",
  "RM TRADING INTERNATIONAL",
  "FAMOUS TELECOM",
  "JONY TELECOM",
  "JOY ELECTRONICS",
  "SARGAM",
  "FARUK ELECTRONICS",
  "AVERTEX ELECTRONICS",
  "FANTASY TELECOM",
  "JASTEL",
  "I POINT BD",
  "EXECUTIVE MACHINES LIMITED",
  "GIZMO ARENA",
  "ONLINE ZONE",
  "VERAZ",
  "KRY INTERNATIONAL",
  "WALK & TALK",
  "NAIMA TELECOM",
  "Gadget House",
  "Mobile Museum",
  "Gadget & Phone",
  "Generation Apple bd",
  "Rio International",
  "Bushra Phone",
  "Alpha Gadget",
  "E-Tel",
  "Cell Garden",
  "Jack N Gadget",
  "Cell Gadget BD",
  "Gadget Shop",
  "UNAYSAH Enterprise",
  "Mobile Corner",
  "Gadget & Gear",
  "GSM Arena",
  "Galaxy Point",
  "Gadget Zone BD",
  "Gadget Gang",
  "Phones 4 U",
  "Gadget 7",
  "KRY International (Dhaka Zone)",
  "GADGET EXCHANGE POINT",
  "Take & Talk Bd",
  "Gadget N Gadget",
  "Yasra Mobile Bd",
  "KS Gadget Bd",
  "I Touch BD",
  "Phonefinity",
  "Ahnaf Telecom Plus",
  "AL-ISLAM TELECOM",
  "MK International",
  "Q Bit",
  "Brothers Electronics",
  "DARPAN TELECOM",
  "Tech Arrow",
  "Exchange Zone & Gadget",
  "Sony Xperia Mobile",
  "F.M. Telecom",
  "Phonomania",
  "SK Mobile Gator",
  "Smartizo",
  "AB International",
  "Race Flame",
  "Gadget Hub",
  "New Exchange Hub",
  "Gadget Insider",
  "Tech Lab",
  "Mobile Park BD",
  "SMART THINK",
  "Apple N Gadget",
  "Vertex Technology",
  "Top Gear BD",
  "Exchange Pro",
  "Gadget Haven BD",
  "Phone Museum",
  "Tech Today",
  "Live Exchange",
  "Galaxy Communications",
  "Mobile House",
  "Mahi Mobile Technology",
  "Telephone",
  "Gadget Fixit BD",
  "Gadget & Lab BD",
  "Device Point BD",
  "Apple Pleasure Ltd",
  "Flash Gadget Gang",
  "I Accessories Home",
  "Custom Mac BD",
  "Al Islam Gadget",
  "Electro Soft",
  "Trust Tech",
  "Techno Palace",
  "BM Computer Technology LTD.",
  "Khan Gadget",
  "Elite Gadget",
  "Aroz Technoloy BD",
  "FITNESS PLUS BANGLADESH",
  "DARAZ BANGLADESH LIMITED",
  "PICKABOO (SILVER WATER TECHNOLOGIES BANGLADESH LTD)",
  "WALLETMIX LTD",
  "Software Shop Limited",
  "PIN POINT PHOTOGRAPHY",
  "GLOBAL IMMIGRATION CONSULTANTS LTD",
  "PURPLE ALGORITHM",
  "AMAZING HOLIDAYS",
  "GIC-MEDICAL TOURISM",
  "HEAVEN TOURS & RESORT LIMITED",
  "HOME TOURS & TRAVELS LTD",
  "LEXUS HOLIDAYS",
  "PLEASURE HOLYDAY LTD",
  "SKY HOLIDAYS",
  "STC-STUDENT & TOURISM CARE",
  "UNITED CONSULTANCY & TOURS",
  "TRYOTEL TRAVELS LTD",
  "Your Travel Ltd.",
  "Glory Air Travels",
  "Glory Holidays",
  "Just Holidays Ltd.",
  "EXCLUSIVE GAMES ZONE",
  "CAMERA LAND",
  "STAR TECH & ENGINEERING LTD",
  "Wasi Computers",
  "LAPTOP STUDIO",
  "ASGAR ALI HOSPITAL",
  "IMPERIAL HOSPITAL LTD.",
  "Este Medical Bangladesh Limited",
  "Rabson Care Limited",
  "BRB Hospitals Limited",
  "CAR DOCTOR",
  "SPRING LPG",
  "GREEN FUEL CNG & LPG CONVERSION CENTER",
  "BAJAJ COLLECTION",
  "SPEEDOZ LTD.",
  "SAMIYA ENTERPRISE",
  "BESTCOM (LE ROYAL, LE MERIDIEN DHAKA)",
  "BB Convention Hall",
  "ROYAL TULIP SEA PEARL BEACH RESORT & SPA",
  "Tanvir International",
  "Osman Telecom",
  "IT Store",
  "Mobile Gadget",
  "Shiam Electronics",
  "PQ",
  "Apple Touch Bd",
  "Mobile Buzz BD",
  "Gadget Station",
  "KD International",
  "Trust Point",
  "Mitali Electronics",
  "iStore",
  "Smartphone Exchange",
  "Shaun's International",
  "Gadget Monkey BD",
  "Unboxing Tech",
  "Digital Shop",
  "Gadget Global",
  "Ar International",
  "Gollachut TeleCare",
  "Rakib Electronics",
  "TELE PARK",
  "TechnoCraft Gadget Store",
  "Ujala Point",
  "TVS Auto Bangladesh Ltd",
  "Momo Inn",
  "Desh Logistics Co.Ltd( Best Buy, Vision, Regal, Sports, Easybuild)",
  "Apple Empire Bd",
  "M/S Mukul Trading",
  "Vista Electronic",
  "Vroom Services Limited",
  "AVERTEX",
  "ALIF Jewellers & Diamond",
  "Gadget Factory",
  "Barisal Enterprise",
  "Minister Hi-Tech Park Electronics Ltd",
  "S.M. TELECOM",
  "FAMOUS BD",
  "R.S. ELECTRONICS",
  "GREAT ELECTRONIC.",
  "KHAN FURNITURE MART",
  "Union Tourism & Travels Ltd",
  "HAROUN TELECOM",
  "DERA Resort & Spa  (Manikgonj)",
  "DERA Resort & Spa  (Cox's Bazar)",
  "PACIFIC TRADING",
  "M/s Shahina Furniture Gallery",
  "CHOWDHURY  ELECTRONICS",
  "M.K. Electronics",
  "Water Garden Resort & Spa",
  "Grand Sylhet Hotel & Resort",
  "ELECTRONICS CITY",
  "GOOD ELECTRONICS",
  "Chuti Resort (Gazipur)",
  "Chuti Resort (Purbachal)",
  "MIRPUR TELECOM",
  "BROTHERS GADGET",
  "B.M.A Electronics",
  "ELECTRONICS POINT",
  "AKHTAR FURNISHERS LTD",
  "DELTA  FURNISHERS LTD",
  "COMFORT FURNITURE SOLUTION",
  "A R GADGET",
  "Gadget & Gallery",
  "TAIBA ENTERPRISE",
  "Hamsha Electronics",
  "AQIB Electronics",
  "T.S ELECTRONICS",
  "Smart Technologies (BD) Ltd. (SONY-SMART)",
  "THE DIAMOND EXPERTS",
  "SAAFWAN DENTAL & ORTHO DONTICS",
  "SHOPNIL SHINDHU",
  "Universal Trading",
  "ATHENA'S furniture & home decor",
  "GRACE COX SMART HOTEL",
  "Home center",
  "Mobile World",
  "PAY STATION",
  "RIYA ELECTRONICS",
  "KARNAPHULI WHEELS LIMITED",
  "SHIP INTERNATIONAL HOSPITAL",
  "ASIAN FURNITURE",
  "MOBILE MART",
  "GULSHAN GADGET",
  "MOBILE MELA",
  "NS INTERNATIONAL MOBILE STORE",
  "Cosmos Holiday",
  "Shayan Resort",
  "HAQUE FAMILY MART",
  "PRIME ELECTRONICS",
  "WHOLESALE ELECTRONICS CITY",
  "WHOLESALE E-MART",
  "MOBILE LAND-2",
  "DIAMOND PALACE LTD",
  "DVICE",
  "MAHIMA TOURS & TRAVELS",
  "RAJLAXMI JEWELLERS",
  "NEW AMIN SMART ZONE",
  "N.S. ELECTRONICS",
  "MOLLAH TELECOM",
  "M H ELECTRONICS",
  "FANCY",
  "SHAREE CENTER",
  "SHOPNO TOUR",
  "BHAI BHAI ELECTRONICS",
  "iStore Ltd",
  "Furniture Concept & interior limited",
  "RIFAT INTERNATIONAL",
  "M/S ZOADDAR ENTERPRISE",
  "ARIF TELECOM",
  "AB AUTO TRADERS-2",
  "'ZARA FURNITURE''",
  "WOOD MARC FURNITURE LTD",
  "VLCC",
  "SHAMI MOTORS",
  "FEMINA FLAUNT BD",
  "EXCHANGE ZONE & GADGET",
  "HATIM STEEL STRUCTURE LTD",
  "NAKSHATRA GOLD",
  "ZAMAN FURNITURE",
  "MOBILE BANGLADESH",
  "ZAARA GOLD",
  "PUROBI DAI GOLD",
  "HF INTERNATION",
  "MEDALLION FURNITURE & INTERIOR",
  "ELECTRA HUB",
  "SHARIF ELECTRONICS",
  "MULTIBRAAND WORKSHOP LTD",
  "MAHIMA TOURS & TRAVELS",
  "IMOHOLIDAYS",
  "VITASKIN",
  "TIRUMALA Gold & DIAMONDS",
  "SWIFT CODE IT SOLUTION",
  "GENERAL ELECTRONICS",
  "SHURJOMUKHI LIMITED (SHURJOPAY)",
  "RAJ LAPTOP GALLERY",
  "INSTYLE",
  "SAMSUL HUDA TRADERS",
  "HAIER BANGLADESH LTD",
  "M/S FAHIM ELECTRONICS",
  "GADGET & PARK",
  "CELL TECH BD",
  "SOFT TECH INNOVATION LIMITED(AAMAR PAY)",
  "ARA ELECTRONICS",
  "MOBILE MEDIA",
  "KABIR & BROTHERS TRADING",
  "PHONE CRAFT",
  "BESTU",
  "DAFFODIL COMPUTERS LTD",
  "AKASH ELECTRONICS",
  "GADGET GLOBE",
  "PANEL ENTERPRISE",
  "SR ELECTONICS",
  "ASIA MOTORS",
  "Hotel Star Pacific"
]

export const mockOfficers = [
  'Syful Islam',
  'Tawhid Chowdhury',
  'Nurul Alam Khan',
  'Zafirul Islam Mondol'
]

